(lang dune 3.20)

(name ocaml_tennis)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Max Blum-Campo <max.blum@gmail.com>")

(maintainers "Max Blum-Campo <max.blum@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name ocaml_tennis)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
